use bytes::Bytes;

/// Maximum RTP packet size for SMPTE 2022-2 (7 x 188 byte TS packets + 12 byte RTP header)
pub const MAX_RTP_PACKET_SIZE: usize = 1500;

/// Broadcast channel capacity for fan-out
pub const BROADCAST_CHANNEL_CAPACITY: usize = 2048;

/// The packet that flows through broadcast channels.
///
/// Carries either:
/// - **RTP-wrapped TS** (SMPTE ST 2022-2): `data` includes the 12+ byte RTP header
///   followed by MPEG-2 TS packets. `sequence_number` and `rtp_timestamp` are parsed
///   from the RTP header.
/// - **Raw TS** (e.g. from OBS, Haivision, srt-live-transmit): `data` contains raw
///   188-byte MPEG-2 TS packets with no RTP header. `sequence_number` is synthetically
///   generated by the input for stats/ordering. `is_raw_ts` is set to true.
///
/// Outputs must check `is_raw_ts` to determine whether to strip an RTP header or
/// forward the data as-is.
#[derive(Clone, Debug)]
pub struct RtpPacket {
    /// Raw packet data — either RTP header + TS payload, or raw TS bytes.
    pub data: Bytes,
    /// RTP sequence number (from header if RTP, synthetic if raw TS).
    pub sequence_number: u16,
    /// RTP timestamp (from header if RTP, synthetic from wall clock if raw TS).
    pub rtp_timestamp: u32,
    /// Monotonic receive time in microseconds (for stats/throughput).
    pub recv_time_us: u64,
    /// True when the data is raw TS (no RTP header). Outputs that strip RTP
    /// headers should skip stripping when this is set.
    pub is_raw_ts: bool,
}
