// Copyright (c) 2026 Softside Tech Pty Ltd. All rights reserved.
// SPDX-License-Identifier: AGPL-3.0-or-later

use bytes::Bytes;

/// Maximum RTP packet size for SMPTE 2022-2 (7 x 188 byte TS packets + 12 byte RTP header)
pub const MAX_RTP_PACKET_SIZE: usize = 1500;

/// Broadcast channel capacity for fan-out — the `Standard` tier of
/// [`crate::config::models::BandwidthProfile`].
///
/// Sized for TS-class contribution / distribution flows (up to ~500 Mbps
/// compressed video). At 1316 bytes per RTP packet (7×188 TS + 12 RTP
/// header), 16 384 slots ≈ 21 MB buffer providing ~3.4 seconds at
/// 50 Mbps, ~344 ms at 500 Mbps, or ~56 ms at 3 Gbps. Slow subscribers
/// receive `RecvError::Lagged` and drop — the input is never blocked.
///
/// **Per-flow override**: when [`crate::config::models::FlowConfig::bandwidth_profile`]
/// is set (or auto-derived to `HighBitrate` / `Uncompressed`) the
/// runtime uses [`crate::config::models::BandwidthProfile::broadcast_capacity`]
/// instead of this constant — see
/// [`crate::engine::bandwidth_profile::resolve_for_flow`]. This constant
/// remains the fallback for code paths that don't have a flow context
/// (tests, isolated channel construction).
#[allow(dead_code)]
pub const BROADCAST_CHANNEL_CAPACITY: usize = 16_384;

/// The packet that flows through broadcast channels.
///
/// Carries either:
/// - **RTP-wrapped TS** (SMPTE ST 2022-2): `data` includes the 12+ byte RTP header
///   followed by MPEG-2 TS packets. `sequence_number` and `rtp_timestamp` are parsed
///   from the RTP header.
/// - **Raw TS** (e.g. from OBS, Haivision, srt-live-transmit): `data` contains raw
///   188-byte MPEG-2 TS packets with no RTP header. `sequence_number` is synthetically
///   generated by the input for stats/ordering. `is_raw_ts` is set to true.
///
/// Outputs must check `is_raw_ts` to determine whether to strip an RTP header or
/// forward the data as-is.
#[derive(Clone, Debug)]
pub struct RtpPacket {
    /// Raw packet data — either RTP header + TS payload, or raw TS bytes.
    pub data: Bytes,
    /// RTP sequence number (from header if RTP, synthetic if raw TS).
    pub sequence_number: u16,
    /// RTP timestamp (from header if RTP, synthetic from wall clock if raw TS).
    pub rtp_timestamp: u32,
    /// Monotonic receive time in microseconds (for stats/throughput).
    pub recv_time_us: u64,
    /// True when the data is raw TS (no RTP header). Outputs that strip RTP
    /// headers should skip stripping when this is set.
    pub is_raw_ts: bool,
    /// Upstream wire sequence number when known. Set on the source leg
    /// of a 2022-7 dual-leg RTP / SRT input so the seq-aware hitless
    /// merger (both transport-layer `redundancy::merger` and pre-bus
    /// `engine::ts_es_hitless`) can dedup + gap-fill against the
    /// authoritative wire-level seq instead of relying on a 200 ms
    /// stall timer. `None` for raw TS over UDP and any input that does
    /// not carry a wire seq.
    pub upstream_seq: Option<u16>,
    /// 2022-7 leg identity (0 = primary, 1 = backup). `None` for
    /// single-leg inputs. Used by the seq-aware merger to attribute
    /// failover events.
    pub upstream_leg_id: Option<u8>,
    /// Sender-set per-packet timestamp in microseconds since the Unix
    /// epoch, when the transport surfaces it. Today: libsrt's
    /// `SRT_MsgCtrl::srctime` reaches us as `Some(_)` on raw-TS-over-
    /// SRT inputs; everywhere else this is `None`. Consumed by
    /// `engine::master_clock::SenderTimestampMaster` for PLL rate
    /// recovery on internet-contribution paths where MPEG-TS PCR
    /// sampled from the bytes after a 200 ms+ latency-buffer release
    /// is too bursty for the PLL to lock cleanly. Sender timestamps
    /// are set at `sendmsg()` time — pre-network-jitter — so they
    /// are not affected by TSBPD release cadence at the receiver.
    pub sender_timestamp_us: Option<i64>,
}
